CREATE TABLE IF NOT EXISTS SALESMAN(
STORE TEXT,
SALESMAN_ID TEXT PRIMARY KEY,
NAME TEXT,
CITY TEXT,
COMMISSION REAL
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
STORE TEXT,
CUSTOMER_ID TEXT PRIMARY KEY,
CUSTOMER_NAME TEXT,
CITY TEXT,
GRADE TEXT,
SALESMAN_ID TEXT
);

CREATE TABLE IF NOT EXISTS ORDERS(
STORE TEXT,
ORDER_NUMBER TEXT PRIMARY KEY,
PURCHASE_AMOUNT REAL,
DATE TEXT,
CUSTOMER_ID TEXT,
SALESMAN_ID
);

INSERT INTO SALESMAN(STORE,SALESMAN_ID,NAME,CITY,COMMISSION) VALUES
('B1','S01','RAMESH','CHENNAI',9800),
('B2','S02','NIRANJAN','BANGALORE',19300),
('B3','S03','RADHIKA','MUMBAI',37890),
('B4','S04','MANSHIKA','DEHLI',38790),
('B5','S05','THIVYA','HYDERABAD',38900);

INSERT INTO CUSTOMER(STORE,CUSTOMER_ID,CUSTOMER_NAME,CITY,GRADE,SALESMAN_ID) VALUES
('B3','C01','KRISHITHA','MUMBAI','GOLD','S03'),
('B4','C02','TANISH','DEHLI','PLATINUM','S04'),
('B1','C03','AMSHU','CHENNAI','SILVER','S01'),
('B5','C04','PRANAV','HYDERABAD','BRONZE','S05'),
('B2','C05','KRITHIK','BANGALORE','GOLD','S02');

INSERT INTO ORDERS(STORE,ORDER_NUMBER,PURCHASE_AMOUNT,DATE,CUSTOMER_ID,SALESMAN_ID) VALUES
('B3','001',40000,'3/6/26','C01','S03'),
('B4','002',78000,'5/6/26','C02','S04'),
('B1','003',56000,'7/6/26','C03','S01'),
('B5','004',78360,'8/6/26','C04','S05'),
('B2','005',93000,'9/6/26','C05','S02');

SELECT CUSTOMER.CUSTOMER_NAME,SALESMAN.NAME,SALESMAN.CITY FROM CUSTOMER JOIN SALESMAN ON CUSTOMER.CITY = SALESMAN.CITY;

SELECT CUSTOMER.CUSTOMER_NAME,SALESMAN.NAME,SALESMAN.SALESMAN_ID FROM CUSTOMER JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID;

SELECT ORDERS.ORDER_NUMBER, ORDERS.CUSTOMER_ID, ORDERS.SALESMAN_ID, CUSTOMER.CUSTOMER_NAME FROM ORDERS JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID JOIN SALESMAN ON ORDERS.SALESMAN_ID = SALESMAN.SALESMAN_ID WHERE CUSTOMER.CITY <> SALESMAN.CITY;

SELECT ORDERS.ORDER_NUMBER,ORDERS.CUSTOMER_ID,CUSTOMER.CUSTOMER_NAME FROM ORDERS JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

SELECT * FROM CUSTOMER 
WHERE GRADE IS NOT NULL;

SELECT CUSTOMER.CUSTOMER_NAME,SALESMAN.NAME FROM CUSTOMER JOIN SALESMAN ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID AND SALESMAN.COMMISSION BETWEEN 9000 AND 10000;

SELECT CUSTOMER.CUSTOMER_ID,ORDERS.ORDER_NUMBER FROM ORDERS JOIN CUSTOMER ON ORDERS.DATE='7/6/26' AND CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID;